config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'consoles/index'

  get 'consoles/new'

  get 'cplayers/index'

  get 'cplayers/new'

  get 'titles/index'

  get 'titles/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
resources :friendships do
  collection do 
    post :friend_accept 
    post :destroy_friendship
  end
end
  match '/index', to: 'static_pages#index', via: 'get', as: :index
  match '/terms-of-service', to: 'static_pages#terms_of_service', via: 'get', as: :terms_of_service
  match '/demo', to: 'static_pages#demo', via: 'get', as: :demo
  
resources :messages do 
collection do
   get :message
  end
end

resources :newsfeeds
resources :genres do
end
resources :channels do
collection do 
  put :delete_channel
  post :create_new_post
  post :follow
  put :unfollow
  end
end

resources :user_details do 
  collection do
    post :update_user
    post :update_pic    
    get :profile
    get :gallery
    get :galleryimage
    post :gallery_pic
    put :del_gallery_pic
    post :pannel_pic
    put :del_pannel_pic
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	 mount_uploader :channel_img, ChannelUploader
	 def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/models/channel_follow.rb
class ChannelFollow < ActiveRecord::Base
end

app/models/channel_post.rb
class ChannelPost < ActiveRecord::Base
end

app/models/console.rb
class Console < ActiveRecord::Base
end

app/models/cplayer.rb
class Cplayer < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	mount_uploader :pic, GalleryUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/pannel.rb
class Pannel < ActiveRecord::Base
	mount_uploader :pannel_img, PannelUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :genres
  has_many :titles
  has_many :cplayers
  has_many :consoles
  has_many :channels
  acts_as_taggable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  
  #after_create :send_mail
  mount_uploader :profile_pic, ProfileUploader
  
  # def send_mail
  #   UserMailer.registration_email(self).deliver
  # end

    def self.all_except(user)
  		where.not(id: user)
	  end

    def self.search(search)
      where("first_name LIKE ?", "%#{search}%")
    end


    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        #user.name = auth.info.name   # assuming the user model has a name
        #user.image = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end



 end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all.order('created_at DESC')
  	if params[:search]
      @channels = Channel.search(params[:search]).order("created_at DESC")
    else
      @channels = Channel.all.order('created_at DESC')
    end
  end

  def new
  	@channel= Channel.new
  end

  def create
  	@channel = Channel.new(channel_params)
  	@channel.save
  	redirect_to @channel
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def show
  	@channel = Channel.find(params[:id])
  	@channel_posts = ChannelPost.where(:channel_id => @channel.id)
    @fol = ChannelFollow.where(:user_id => current_user.id, :channel_id => @channel.id)
  end

  def update
    @channel = Channel.find(params[:id])
    @channel.update(channel_params)
    redirect_to channel_path
  end

  def delete_channel
    @channel = Channel.find(params[:id])
    @channel.destroy!
    @channel_post = ChannelPost.where(:channel_id => @channel.id)
    @channel_post.each do |cp|
      cp.destroy!
    end
    @channel_fol = ChannelFollow.where(:channel_id => @channel.id)
    @channel_fol.each do |cf|
      cf.destroy!
    end
    
    redirect_to @channel
  end

  def create_new_post
  	@channel_post= ChannelPost.new
  	@channel_post.channel_id = params[:channel_id]
  	@channel_post.user_id = current_user.id
  	@channel_post.comment= params[:comment]
  	@channel_post.save
  	redirect_to :back
  end

  def follow
    @follow = ChannelFollow.new
    @follow.user_id = current_user.id
    @follow.channel_id = params[:channel_id]
    @follow.save
    redirect_to :back
  end

  def unfollow
    @unfollow = ChannelFollow.where(:user_id => current_user.id, :channel_id => params["channel_id"])
    @unfollow[0].destroy!
    redirect_to :back
  end

  private
  def channel_params
  	params.require(:channel).permit(:name, :description, :channel_type, :channel_img, :user_id) 	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/cplayers_helper.rb
module CplayersHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/channels/create_new_post.js.erb
$("#channel_post").append("<%= escape_javascript(render(:partial => @channel_posts)) %>");
$("#new_message")[0].reset();

app/views/channels/edit.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!-- ==========================
    	JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>

<div class="container hidden-xs">
	<div class="header-title">
    	<div class="pull-left">
    		<h1><a href="#"><span class="text-primary">Edit</span>Channel</a></h1>
        </div>
    </div>
</div>

<div class="container">
    <section class="content-wrapper">
    	  <div class="row">
    	  	<div class="col-sm-12">
<% if @channel.user_id == current_user.id %>
    <%= form_for @channel , :html => {:multipart => true} do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    	<div class="form-group"> 
    	    <div class="row">               
    	        <label class="control-label col-sm-4 col-md-3">Channel Name</label>
    	        <div class="col-sm-6 col-md-5">
    	            <%= f.text_field :name, tabindex: "1", class: "form-control", placeholder: 'Enter The Channel Name', autofocus: true, required: true %>
    	        </div>
    	    </div>
    	</div>
    	<div class="form-group"> 
    	    <div class="row">               
    	        <label class="control-label col-sm-4 col-md-3">Channel Description</label>
    	        <div class="col-sm-6 col-md-5">
    	            <%= f.text_area :description, tabindex: "2", class: "form-control", placeholder: 'Put The Description', required: true %>
    	        </div>
    	    </div>
    	</div>
    	<div class="form-group">
    	    <div class="row">                
    	        <label class="control-label col-sm-4 col-md-3">Channel Type</label>
    	        <div class="col-sm-6 col-md-5">                                
    	        <%= f.select :channel_type, [['Game'], ['Community'], ['Team'], ['Top Players']], {}, tabindex: "3", class: "form-control" %>                                
    	        </div>
    	    </div>
    	</div>
        <div class="form-group"> 
            <div class="row">               
                <label class="control-label col-sm-4 col-md-3">Channel Image</label>
                <div class="col-sm-6 col-md-5">
                    <%= f.file_field :channel_img, tabindex: "4", class: "form-control" %>
                </div>
            </div>
        </div>
         
    	<div class="row">
            <div class="actions">
            	<div class="col-xs-6 col-sm-5 col-md-4">                                        
                    <%= link_to 'Cancel', channel_path, :class => 'btn btn-primary', tabindex: "6" %>
                </div>
                <div class="col-xs-6 col-sm-5 col-md-4">
                        <%= f.submit 'Update', :class => 'btn btn-primary',tabindex: "5" %>
                </div>             
            </div>
        </div>

    <% end %>
<% else %>
    <h1 class="text-center">You have no rights to Edit this channel.</h1>
<% end %>
			</div>
		</div>
	</section>
</div>
   
<%= content_for :general_js do %>       
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/owl.carousel.js"></script>
    <script src="/assets/jquery.magnific-popup.min.js"></script>
    <script src="/assets/creative-brands.js"></script>
    <script src="/assets/jquery.vegas.min.js"></script>
    <script src="/assets/twitterFetcher_min.js"></script>
    <script src="/assets/jquery.countdown.min.js"></script>
   
<% end %>

app/views/channels/index.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!-- ==========================
    	JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>



<div class="container">
	<div class="header-title">
    	<div class="pull-left">
    		<h1><span class="text-primary">C</span>hannels</h1> 
        </div>
    </div>
</div>

<div class="container">
    <section class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <%= form_tag(channels_path, :method => "get",class: "form-inline") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Channel",class: "form-control", required: true, oninvalid: "setCustomValidity('Write a channel name')", onchange: "try{setCustomValidity('')}catch(e){}"  %>
                <%= submit_tag "Search", class: "btn btn-primary" %>
                <%= link_to "Create a channel", new_channel_path %>
                <% end %>

            <% if @channels.present? %>
                <ul class="nav nav-sidebar">
                    <% @channels.each do |channel| %>
                    <li><%= link_to channel.name, channel_path(:id => channel.id) %></li>
                    <% end %>
                </ul>
            <% elsif params[:search] == nil %>
                <p></p>
            <% else %>
              <p>There are no channels containing name <%= params[:search] %>. Click <%= link_to("here", channels_path, method: :get) %> to search again.</p>
            <% end %>

            </div>
        </div>
    </section>
</div>



   
<%= content_for :general_js do %>       
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/owl.carousel.js"></script>
    <script src="/assets/jquery.magnific-popup.min.js"></script>
    <script src="/assets/creative-brands.js"></script>
    <script src="/assets/jquery.vegas.min.js"></script>
    <script src="/assets/twitterFetcher_min.js"></script>
    <script src="/assets/jquery.countdown.min.js"></script>
   
<% end %>

app/views/channels/new.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!-- ==========================
    	JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>

<div class="container hidden-xs">
	<div class="header-title">
    	<div class="pull-left">
    		<h1><a href="#"><span class="text-primary">Create</span>Channels</a></h1>
        </div>
    </div>
</div>

<div class="container">
    <section class="content-wrapper">
    	  <div class="row">
    	  	<div class="col-sm-12">
<%= form_for @channel , :html => {:multipart => true} do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
	<div class="form-group"> 
	    <div class="row">               
	        <label class="control-label col-sm-4 col-md-3">Channel Name</label>
	        <div class="col-sm-6 col-md-5">
	            <%= f.text_field :name, tabindex: "1", class: "form-control", placeholder: 'Enter The Channel Name', autofocus: true, required: true %>
	        </div>
	    </div>
	</div>
	<div class="form-group"> 
	    <div class="row">               
	        <label class="control-label col-sm-4 col-md-3">Channel Description</label>
	        <div class="col-sm-6 col-md-5">
	            <%= f.text_area :description, tabindex: "2", class: "form-control", placeholder: 'Put The Description', required: true %>
	        </div>
	    </div>
	</div>
	<div class="form-group">
	    <div class="row">                
	        <label class="control-label col-sm-4 col-md-3">Channel Type</label>
	        <div class="col-sm-6 col-md-5">                                
	        <%= f.select :channel_type, [['Game'], ['Community'], ['Team'], ['Top Players']], {}, tabindex: "3", class: "form-control" %>                                
	        </div>
	    </div>
	</div>
    <div class="form-group"> 
        <div class="row">               
            <label class="control-label col-sm-4 col-md-3">Channel Image</label>
            <div class="col-sm-6 col-md-5">
                <%= f.file_field :channel_img, tabindex: "4", class: "form-control", required: true %>
            </div>
        </div>
    </div>
     
	<div class="row">
        <div class="actions">
        	<div class="col-xs-6 col-sm-5 col-md-4">                                        
                <%= link_to 'Cancel', root_path, :class => 'btn btn-primary', tabindex: "6" %>
            </div>
            <div class="col-xs-6 col-sm-5 col-md-4">
                    <%= f.submit 'Submit', :class => 'btn btn-primary',tabindex: "5" %>
            </div>             
        </div>
    </div>

<% end %>
			</div>
		</div>
	</section>
</div>
   
<%= content_for :general_js do %>       
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/owl.carousel.js"></script>
    <script src="/assets/jquery.magnific-popup.min.js"></script>
    <script src="/assets/creative-brands.js"></script>
    <script src="/assets/jquery.vegas.min.js"></script>
    <script src="/assets/twitterFetcher_min.js"></script>
    <script src="/assets/jquery.countdown.min.js"></script>
   
<% end %>

app/views/channels/show.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!-- ==========================
        JS 
    =========================== -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>

<div class="container">
    <div class="header-title">
        <div class="pull-left">
            <h1><a href="#"><span class="text-primary">C</span>hannel</a></h1>
        </div>
    </div>
</div>

<div class="container">
    <section class="content-wrapper">
          <div class="row">
            <div class="col-sm-12 text-right">
<% if @channel.user_id == current_user.id %>
<%= link_to "Edit", edit_channel_path(@channel), :class => 'btn btn-primary' %>
<%= link_to "Delete Channel", delete_channel_channels_path(:id => @channel.id), :method => :put, data: {confirm: "Are you sure you want to delete this channel ?"}, :class => 'btn btn-primary' %>
<% end %>
            </div>
            <div class="col-sm-12">
<span>Channel Name: </span><%= @channel.name %><br>
<span>Channel Description: </span><%= @channel.description %><br>
<span>Channel Type: </span><%= @channel.channel_type %><br>
<span>Channel image: </span><%= image_tag @channel.channel_img_url %><br>
<span class= "text-capitalize">Posted by:
            <% postby = User.find(@channel.user_id) %>
         <strong><%= postby.first_name %> <%= postby.last_name %></strong>
</span>

<% if @fol.exists? %>
<span><%= link_to 'Unfollow', unfollow_channels_path(:user_id => current_user.id, :channel_id => @channel.id), :method => :put %></span>

<% else %>
<span><%= link_to 'Follow', follow_channels_path(:user_id => current_user.id, :channel_id => @channel.id), :method => "post" %></span>
<% end %>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">

<!-- <div id="channel_post">
  <%= render :partial => 'channels/channelpost', :collection => @channel_posts %>
</div> -->
<% @channel_posts.each do |c| %>
    <%= User.find(c.user_id).first_name %> :
    <%= c.comment %>
    <br>
<% end %>


<%= form_tag create_new_post_channels_path, method: :post, class: "form-horizontal" do  %>
<%= hidden_field_tag :channel_id , params[:id] %>
<div class="form-group">
  <label class="control-label col-sm-3">Comments</label>
  <div class="col-sm-9">                                  
      <%= text_area_tag "comment", nil, type:"text", tabindex: "1", class: "form-control",   placeholder: 'Write your comment' %>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-xs-6 col-sm-4">
    <%= submit_tag 'Submit', :class => 'btn btn-primary' %>
  </div>
</div>

<% end %>
            </div>
        </div>
    </section>
</div>
   
<%= content_for :general_js do %>       
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/owl.carousel.js"></script>
    <script src="/assets/jquery.magnific-popup.min.js"></script>
    <script src="/assets/creative-brands.js"></script>
    <script src="/assets/jquery.vegas.min.js"></script>
    <script src="/assets/twitterFetcher_min.js"></script>
    <script src="/assets/jquery.countdown.min.js"></script>
   
<% end %>