config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'consoles/index'

  get 'consoles/new'

  get 'cplayers/index'

  get 'cplayers/new'

  get 'titles/index'

  get 'titles/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
resources :friendships do
  collection do 
    post :friend_accept 
    post :destroy_friendship
  end
end
  match '/index', to: 'static_pages#index', via: 'get', as: :index
  match '/terms-of-service', to: 'static_pages#terms_of_service', via: 'get', as: :terms_of_service
  match '/demo', to: 'static_pages#demo', via: 'get', as: :demo
  
resources :messages do 
collection do
   get :message
  end
end

resources :newsfeeds
resources :genres do
end
resources :channels do
collection do 
  put :delete_channel
  post :create_new_post
  post :follow
  put :unfollow
  end
end

resources :user_details do 
  collection do
    post :update_user
    post :update_pic    
    get :profile
    get :gallery
    get :galleryimage
    post :gallery_pic
    put :del_gallery_pic
    post :pannel_pic
    put :del_pannel_pic
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	 mount_uploader :channel_img, ChannelUploader
	 def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/models/channel_follow.rb
class ChannelFollow < ActiveRecord::Base
end

app/models/channel_post.rb
class ChannelPost < ActiveRecord::Base
end

app/models/console.rb
class Console < ActiveRecord::Base
end

app/models/cplayer.rb
class Cplayer < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	mount_uploader :pic, GalleryUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/pannel.rb
class Pannel < ActiveRecord::Base
	mount_uploader :pannel_img, PannelUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :genres
  has_many :titles
  has_many :cplayers
  has_many :consoles
  has_many :channels
  acts_as_taggable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  
  #after_create :send_mail
  mount_uploader :profile_pic, ProfileUploader
  
  # def send_mail
  #   UserMailer.registration_email(self).deliver
  # end

    def self.all_except(user)
  		where.not(id: user)
	  end

    def self.search(search)
      where("first_name LIKE ?", "%#{search}%")
    end


    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        #user.name = auth.info.name   # assuming the user model has a name
        #user.image = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end



 end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController
	# def index
 #    	@feeds = Newsfeed.all
 #  	end

  	def create
    	@feed = Newsfeed.create!(feed_params)
      redirect_to :back
  	end

  	def show
  		@newsfeed = Newsfeed.find(params[:id])
  	end

    def edit
      @newsfeed = Newsfeed.find(params[:id])
    end

    def update
      @newsfeed = Newsfeed.find(params[:id])
      @newsfeed.update(feed_params)    
      redirect_to index_path
    end

	private

  	def feed_params
    	params.require(:newsfeed).permit(:post, :feed_title, :image, :user_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/cplayers_helper.rb
module CplayersHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/newsfeeds/_newsfeed.html.erb

<article class="post">
	<div class="post-date-wrapper">
    	<div class="post-date">
        	<div class="day"><%= newsfeed.updated_at.strftime("%d") %></div>
        	<div class="month"><%= newsfeed.updated_at.strftime("%b %Y") %></div>
        </div>
    </div>
    <div class="post-body">
        <!-- <h2><%= newsfeed.feed_title %></h2> -->

        <p><%= image_tag newsfeed.image_url %>
        	<%= newsfeed.post %></p>
        <div class="post-info">
            <span class= "text-capitalize">Posted by:
                <% post_by = User.find(newsfeed.user_id) %>
             <strong><%= post_by.first_name %> <%= post_by.last_name %></strong></span>

            <%= link_to "View More", newsfeed_path(newsfeed.id), class: "btn btn-inverse" %>
            <% if current_user == post_by %>
            <%= link_to "Edit", edit_newsfeed_path(newsfeed.id), class: "btn btn-inverse" %>
            <% end %>
            
        </div>
    </div>
</article>

app/views/newsfeeds/create.js.erb
$("#feed_post").append("<%= escape_javascript(render(:partial => @feed)) %>");
$("#new_newsfeed")[0].reset();

app/views/newsfeeds/edit.html.erb
<%= content_for :general_css do %>
<link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/assets/animate.css" rel="stylesheet" type="text/css">
<link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
<link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
<link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
<link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
<link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
<link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
<link href="/assets/custom.css" rel="stylesheet" type="text/css">

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<% end %>  

<div class="container">
    <section class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
    <h4>Edit your thoughts: </h4>

    <%= form_for @newsfeed, :html => {:multipart => true}, authenticity_token: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="form-group">
            <%= f.text_field :feed_title, class: "form-control", required: true %>
        </div>
        <div class="form-group">
            <%= f.text_area :post, class: "form-control", required: true, rows: "15" %>
        </div>
        <div class="form-group">
            <%= f.file_field :image, class: "form-control" %>
        </div>
        <%= link_to "Cancel", index_path, class: "btn btn-primary" %>
            <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
                </div>
			</div>
		</div>
	</section>
</div>
<% content_for :general_js do %>       
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/owl.carousel.js"></script>
<script src="/assets/jquery.magnific-popup.min.js"></script>
<script src="/assets/creative-brands.js"></script>
<script src="/assets/jquery.vegas.min.js"></script>
<script src="/assets/twitterFetcher_min.js"></script>
<script src="/assets/jquery.countdown.min.js"></script>
<script src="/assets/custom.js"></script>
<% end %>

app/views/newsfeeds/show.html.erb
<%= content_for :general_css do %>
<link href="assets/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="assets/animate.css" rel="stylesheet" type="text/css">
<link href="assets/owl.carousel.css" rel="stylesheet" type="text/css">
<link href="assets/owl.theme.css" rel="stylesheet" type="text/css">
<link href="assets/owl.transitions.css" rel="stylesheet" type="text/css">
<link href="assets/creative-brands.css" rel="stylesheet" type="text/css">
<link href="assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
<link href="assets/magnific-popup.css" rel="stylesheet" type="text/css">
<link href="assets/custom.css" rel="stylesheet" type="text/css">

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<% end %>  
kill

<% content_for :general_js do %>       
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="assets/bootstrap.min.js"></script>
<script src="assets/owl.carousel.js"></script>
<script src="assets/jquery.magnific-popup.min.js"></script>
<script src="assets/creative-brands.js"></script>
<script src="assets/jquery.vegas.min.js"></script>
<script src="assets/twitterFetcher_min.js"></script>
<script src="assets/jquery.countdown.min.js"></script>
<script src="assets/custom.js"></script>
<% end %>