config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'consoles/index'

  get 'consoles/new'

  get 'cplayers/index'

  get 'cplayers/new'

  get 'titles/index'

  get 'titles/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
resources :friendships do
  collection do 
    post :friend_accept 
    post :destroy_friendship
  end
end
  match '/index', to: 'static_pages#index', via: 'get', as: :index
  match '/terms-of-service', to: 'static_pages#terms_of_service', via: 'get', as: :terms_of_service
  match '/demo', to: 'static_pages#demo', via: 'get', as: :demo
  
resources :messages do 
collection do
   get :message
  end
end

resources :newsfeeds
resources :genres do
end
resources :channels do
collection do 
  put :delete_channel
  post :create_new_post
  post :follow
  put :unfollow
  end
end

resources :user_details do 
  collection do
    post :update_user
    post :update_pic    
    get :profile
    get :gallery
    get :galleryimage
    post :gallery_pic
    put :del_gallery_pic
    post :pannel_pic
    put :del_pannel_pic
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	 mount_uploader :channel_img, ChannelUploader
	 def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/models/channel_follow.rb
class ChannelFollow < ActiveRecord::Base
end

app/models/channel_post.rb
class ChannelPost < ActiveRecord::Base
end

app/models/console.rb
class Console < ActiveRecord::Base
end

app/models/cplayer.rb
class Cplayer < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	mount_uploader :pic, GalleryUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/pannel.rb
class Pannel < ActiveRecord::Base
	mount_uploader :pannel_img, PannelUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :genres
  has_many :titles
  has_many :cplayers
  has_many :consoles
  has_many :channels
  acts_as_taggable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  
  #after_create :send_mail
  mount_uploader :profile_pic, ProfileUploader
  
  # def send_mail
  #   UserMailer.registration_email(self).deliver
  # end

    def self.all_except(user)
  		where.not(id: user)
	  end

    def self.search(search)
      where("first_name LIKE ?", "%#{search}%")
    end


    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        #user.name = auth.info.name   # assuming the user model has a name
        #user.image = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end



 end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
	
	def edit
		@user = current_user
	end

	def update_user
		@user = current_user
		@user.addr = params[:addr]
		@user.phone = params[:phone]
		@user.gender = params[:gender]
		@user.status = params[:status]
		@user.about = params[:about]
		@user.save
		
		redirect_to :back

	end

	def update_pic
		@user = current_user
		@user.profile_pic = params[:profile_pic]
		@user.save
      	redirect_to :back
	end

	def profile
		@user = User.find(params[:id])
		#@users = User.all_except(current_user)
	    @genres = Genre.all
	    @mychannels = Channel.where(:user_id => @user.id)
	    @channels = ChannelFollow.where(:user_id => @user.id)
	    @friends_rq_sent = Friendship.where(:user_id => @user.id, :status => 1)
	    @friends_rq_recieved = Friendship.where(:user_id => @user.id, :status => 3)
	    @friends = Friendship.where(:user_id => @user.id, :status => 2)
		if params[:search]
	    	@users = User.search(params[:search])
	  	
	  	end

	end

	def gallery
		@channels = Channel.all.order('created_at DESC')
	    @user = User.find(params[:id])
	    @pictures = Gallery.where(:user_id => @user.id)
	end

	def gallery_pic
		@gpic = Gallery.new
		@gpic.user_id = current_user.id
		@gpic.pic = params[:pic]
		@gpic.save
      	redirect_to :back
	end

	def galleryimage
		@user = User.find(params[:id])
	    @pictures = Gallery.where(:user_id => @user.id)
	end

	def del_gallery_pic
		@g_id = Gallery.find(params[:format])
		@g_id.destroy!
		redirect_to :back
	end

	def pannel_pic
		@ppic = Pannel.new
		@ppic.user_id = current_user.id
		@ppic.pannel_title = params[:pannel_title]
		@ppic.pannel_img = params[:pannel_img]
		@ppic.save
      	redirect_to :back
	end

	def del_pannel_pic
		@p_id = Pannel.find(params[:format])
		@p_id.destroy!
		redirect_to :back
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/cplayers_helper.rb
module CplayersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/gallery.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>

   
    <!-- ==========================
    	TITLE - START 
    =========================== -->
    <div class="container hidden-xs">
    	<div class="header-title">
        	<div class="pull-left">
        		<h1><span class="text-primary">G</span>allery</h1>
            </div>
        </div>
    </div>
<!-- ===== TITLE - END ===== -->
    


<!-- ===== CONTENT - START ===== -->
<div class="container">
    <section class="content-wrapper">
    	<div class="row">
        
        	<!-- SIDEBAR - START -->
        	<!-- <div class="col-sm-12"> -->
                
                
                
                <!-- SIDEBAR BOX - START -->
                <!-- <div class="box sidebar-box widget-wrapper">
                	<h3>Latest Tweets</h3>
                    <div id="twitter-wrapper">
                    </div>
                </div> -->
                <!-- SIDEBAR BOX - END -->
                
            <!-- </div> -->
            <!-- SIDEBAR - END -->
            
            <!-- CONTENT BODY - START -->
            <div class="col-sm-12">
                <% if @user == current_user %>
                	<div class="box">
                        <div class="row">                        
                            <div class="col-sm-8">
                                <%= form_tag gallery_pic_user_details_path, :multipart => true, :method=>'post', class: "form-inline" do %>
                                        <div class="form-group"> 
                                            <%= file_field_tag  "pic", class: "form-control", required: true, oninvalid: "setCustomValidity('Choose a photo')", onchange: "try{setCustomValidity('')}catch(e){}" %>
                                        </div>
                                        <div class="form-group"> 
                                           <%= submit_tag "Add" , class: "btn btn-primary" %>
                                        </div>                        
                                <% end %>
                            </div>
                            <div class="col-sm-4 text-right">
                                <% if @pictures.present?  %>
                                <%= link_to "Remove Images", galleryimage_user_details_path(:id =>current_user.id), method: :get, class: "btn btn-primary" %>
                                <% end %>
                            </div>                        
                        </div>              
                    </div>
                <% end %>

            
                    <div class="box">                                            
                        <!-- GALLERY POST - START -->
                        <article class="post gallery-post">
                            <div class="row gallery-page">
                                <% if @pictures.present?  %>
                                    <% for g in @pictures %>
                                        <div class="col-sm-2 text-center">
                                          <%= link_to g.pic_url do %>
                                          <br>
                                            <%= image_tag g.pic_url, class: "img-responsive img-thumbnail img_height" %>
                                          <% end %>
                                        </div>
                                    <% end %>  
                                <% else %>
                                    <% if @user != current_user %>
                                        <h1 class="text-center">No image found</h1>
                                    <% else %>
                                        <h1>Choose a file above to add an image </h1>
                                    <% end %>
                                <% end %>                                                
                            </div>  
                        </article>
                        <!-- GALLERY POST - END -->
                    </div>
            

            </div>
                <!-- CONTENT BODY - END -->
                
        </div>
    </section>
</div>


<%= content_for :general_js do %>     
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/owl.carousel.js"></script>
<script src="/assets/jquery.magnific-popup.min.js"></script>
<script src="/assets/creative-brands.js"></script>
<script src="/assets/jquery.vegas.min.js"></script>
<script src="/assets/twitterFetcher_min.js"></script>
<script src="/assets/jquery.countdown.min.js"></script>
<script src="/assets/custom.js"></script>
<% end %>

app/views/user_details/galleryimage.html.erb
<%= content_for :general_css do %>
    <link href="/assets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/animate.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="/assets/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="/assets/creative-brands.css" rel="stylesheet" type="text/css">
    <link href="/assets/jquery.vegas.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="/assets/custom.css" rel="stylesheet" type="text/css">
    
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<% end %>

   
    <!-- ==========================
        TITLE - START 
    =========================== -->
    <div class="container">
        <div class="header-title">
            <div class="pull-left">
                <h1><span class="text-primary">R</span>emove Images</h1>
            </div>
        </div>
    </div>
<!-- ===== TITLE - END ===== -->
    


<!-- ===== CONTENT - START ===== -->
    <div class="container">
        <section class="content-wrapper">
            <div class="row">
                
                <!-- CONTENT BODY - START -->
                <div class="col-sm-12">
                    <div class="box">                      
                        <div class="row">
                            <% if @pictures.present?  %>
                                <% for g in @pictures %>
                                   <div class="col-sm-2">
                                    <%= image_tag g.pic_url, class: "img-responsive img-thumbnail img_height" %>
                                    <br>
                                    <%= link_to 'Remove', del_gallery_pic_user_details_path(g.id), data: { confirm: 'Are you sure?' }, :method => :put %>
                                    </div> 
                                <% end %>
                            <% else %>                            
                                    <h1 class="text-center">You have no image to delete</h1>
                            <% end %>
                        </div> 
                        <div class="row">
                            <div class="col-sm-12 pad-top1">
                                <%= link_to "Back to gallery", gallery_user_details_path(:id =>current_user.id), method: :get, class: "btn btn-primary" %>
                            </div>
                        </div>                                 
                    </div>                   
                </div>
                <!-- CONTENT BODY - END -->
                
            </div>
        </section>
    </div>


<%= content_for :general_js do %>     
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>
<script src="/assets/owl.carousel.js"></script>
<script src="/assets/jquery.magnific-popup.min.js"></script>
<script src="/assets/creative-brands.js"></script>
<script src="/assets/jquery.vegas.min.js"></script>
<script src="/assets/twitterFetcher_min.js"></script>
<script src="/assets/jquery.countdown.min.js"></script>
<script src="/assets/custom.js"></script>
<% end %>