config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'consoles/index'

  get 'consoles/new'

  get 'cplayers/index'

  get 'cplayers/new'

  get 'titles/index'

  get 'titles/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
resources :friendships do
  collection do 
    post :friend_accept 
    post :destroy_friendship
  end
end
  match '/index', to: 'static_pages#index', via: 'get', as: :index
  match '/terms-of-service', to: 'static_pages#terms_of_service', via: 'get', as: :terms_of_service
  match '/demo', to: 'static_pages#demo', via: 'get', as: :demo
  
resources :messages do 
collection do
   get :message
  end
end

resources :newsfeeds
resources :genres do
end
resources :channels do
collection do 
  put :delete_channel
  post :create_new_post
  post :follow
  put :unfollow
  end
end

resources :user_details do 
  collection do
    post :update_user
    post :update_pic    
    get :profile
    get :gallery
    get :galleryimage
    post :gallery_pic
    put :del_gallery_pic
    post :pannel_pic
    put :del_pannel_pic
  end
end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/channel.rb
class Channel < ActiveRecord::Base
	 mount_uploader :channel_img, ChannelUploader
	 def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/models/channel_follow.rb
class ChannelFollow < ActiveRecord::Base
end

app/models/channel_post.rb
class ChannelPost < ActiveRecord::Base
end

app/models/console.rb
class Console < ActiveRecord::Base
end

app/models/cplayer.rb
class Cplayer < ActiveRecord::Base
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	mount_uploader :pic, GalleryUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/pannel.rb
class Pannel < ActiveRecord::Base
	mount_uploader :pannel_img, PannelUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :genres
  has_many :titles
  has_many :cplayers
  has_many :consoles
  has_many :channels
  acts_as_taggable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  
  #after_create :send_mail
  mount_uploader :profile_pic, ProfileUploader
  
  # def send_mail
  #   UserMailer.registration_email(self).deliver
  # end

    def self.all_except(user)
  		where.not(id: user)
	  end

    def self.search(search)
      where("first_name LIKE ?", "%#{search}%")
    end


    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        #user.name = auth.info.name   # assuming the user model has a name
        #user.image = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end



 end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/cplayers_helper.rb
module CplayersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/views/layouts/_channel_notification.html.erb

<ul class="nav nav-sidebar">
	<% @channels.each do |channel| %>
	<li><%= link_to channel.name, channel_path(:id => channel.id) %></li>
	<% end %>
</ul>

<!-- <li><a href="#">Minecraft<span>18</span></a></li> -->

app/views/layouts/_pannel.html.erb
<div class="container">
	<div class="jumbotron">

    	<div class="jumbotron-panel">
            <div class="row">
                <div class="col-sm-9 pad-bot1">
<% if current_user.id == 1 %>
    <%= form_tag pannel_pic_user_details_path, :multipart => true, :method=>'post', class: "form-inline" do %>
        <div class="form-group"> 
            <%= text_field_tag  "pannel_title", nil, class: "form-control", placeholder: "Title" %>
        </div>
        <div class="form-group"> 
            <%= file_field_tag  "pannel_img", class: "form-control" %>
        </div>
        <div class="form-group"> 
           <%= submit_tag "Add" , class: "btn btn-primary" %>
        </div>
    <% end %>
<% else %>
    <p class="text-primary"><strong>New Release</strong></p>
<% end %>
                </div>
                <div class="col-sm-3 text-right">
<!-- <ul class="brands brands-sm brands-inline brands-circle">
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-twitter"></i></a></li>
    <li><a href=""><i class="fa fa-google-plus"></i></a></li>
</ul> -->
                </div>
            </div>                 
        </div>
            
        <div id="jumbotron-slider">    
<% for p in @pannels %>
    <div class="item">
        <div class="overlay-wrapper">
            <%= image_tag p.pannel_img_url, class: "img-responsive" %>
            <span class="overlay"></span>
            <h2><%= p.pannel_title %><span><%= p.created_at.strftime("%d %b %Y") %></span></h2>
        </div>
        <% if current_user.id == 1 %>
            <%= link_to 'Remove', del_pannel_pic_user_details_path(p.id), data: { confirm: 'Are you sure?' }, :method => :put %>
        <% end %>
    </div>
<% end %>                             
        </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <%= favicon_link_tag 'favicon.png' %>
<title>eLegend</title>
<link rel="shortcut icon" href="/assets/icons/favicon.ico">
<link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png">

<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<%= yield :index_css %>
<%= yield :signin_css %>
<%= yield :general_css %>
<%= csrf_meta_tags %>

</head>
	<body>
    <!-- ==========================
    	HEADER - START 
    =========================== -->
	<header class="navbar navbar-default navbar-fixed-top">
    	<div class="container">
            <% if user_signed_in? %>
            <div class="navbar-header">
            	<a href="index.html" class="navbar-brand visible-xs">eLeagend</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="navbar-collapse collapse">
            	<ul class="nav navbar-nav">
                	<li><a href="/">Home</a></li>
                    <li><%= link_to("Profile", profile_user_details_path(:id =>current_user.id), method: :get) %></li>
                    <li><%= link_to("Message", messages_path, method: :get) %></li>
                    <li><%= link_to("Gallery", gallery_user_details_path(:id =>current_user.id), method: :get) %></li>
                    <li><a href="#">Gaming</a></li>
                    <li><%= link_to("Channels", channels_path, method: :get) %></li>
                    <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gaming</a>
                        <ul class="dropdown-menu">
                        	<li><a href="gaming-team.html"><i class="fa fa-plus"></i>Gaming team</a></li>
                            <li><a href="matches-list.html"><i class="fa fa-plus"></i>List of matches</a></li>
                            <li><a href="match-single.html"><i class="fa fa-plus"></i>Single match</a></li>
                            <li><a href="tournament.html"><i class="fa fa-plus"></i>Tournament</a></li>
                        </ul>
                    </li> -->
                    
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li>
                        <% if current_user.profile_pic_url != nil %>
                        <%= image_tag current_user.profile_pic_url, class: "img-responsive img-circle center-block" %>
                        <% else %>
                        <%= image_tag('profile-img.jpg', class: "img-responsive img-circle center-block") %>
                        <% end %>

                    </li>
                    <li><%= link_to(current_user.first_name,profile_user_details_path(:id =>current_user.id), method: :get) %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, class: "btn btn-inverse", :method => :delete %> </li>
                </ul>
            </div>
            <% else %>
            
            <div class="row">
                <div class="col-sm-6">

            <div class="navbar-header">
                <%= link_to(image_tag("elegend-logo-top.png", alt: "Home"), root_path, method: :get) %>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
                </div>
            <div class="col-sm-6">
            <div class="navbar-collapse collapse">
                
                <div class="pull-right navbar-buttons hidden-xs">                   
                    <div class="box registration-form">
                        
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
<%= devise_error_messages! %>
<% flash.each do |key, value| %>
   <div class="alert alert-success <%= key %>"><%= value %></div>
<% end %>
<div class="col-sm-5">
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter Email", autofocus: true %>
    </div>
</div>
<div class="col-sm-5">
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
</div>
<div class="col-sm-2">
    <div class="form-group">
        <div class="pad-top2">          
        <%= f.submit "Log in", class: "btn btn-primary" %>
        </div>
    </div>
</div>
<div class="col-sm-6">
    <div class="checkbox remember">
     <!--  <label><input type="checkbox"> Remember me on this computer</label></div> -->
      <% if devise_mapping.rememberable? -%>        
          <%= f.check_box :remember_me %>
          <%= f.label "Remember me on this computer" %>    
      <% end -%>
    </div>
</div>
<div class="col-sm-6">
    <a id="reset-password-toggle" class="">Did you forget your password?</a> 
</div>
    <% end %>
                    
    <div class="box registration-form" id="reset-password">
        <h2>Forgotten password</h2>
        <p>Forgot your Password hu? Go ahead and reset your password with your email and try not to forget it next time!</p>

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>

  <div class="form-group">
    <label for="forg_email">Email address</label>
    <%= f.email_field :email, class: "form-control", id: "forg_email", placeholder: "Enter email", autofocus: true %>
  </div>

  <div class="form-group actions">
    <%= f.submit "Reset password", class: "btn btn-primary" %>
  </div>
<% end %>

    </div>
                </div>
                    
                </div>
            </div>
        </div>
    </div>
            <% end %>
        </div>
    </header>
    <!-- ==========================
    	HEADER - END 
    =========================== --> 
 <!--
<% if notice %>
    <div class="container">
        <div class="row notify">
            <div class="col-sm-12">
        <p class="alert alert-success">
            <%= notice %>
        </p>
            </div>
        </div>
    </div>
<% end %>
-->
<%= yield %>

<!-- ==========================
    	FOOTER - START 
    =========================== -->
    <div class="container">
    	<div class="footer-boxes">
        	<div class="row">
                        
                <!-- FOOTER BOX - START -->
            	<!--<div class="col-md-4 hidden-xs hidden-sm">-->
                	<!--<div class="box">-->
                    	<!--<h4>About Us</h4>-->
                        <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac.</p>-->
                    <!--</div>-->
            	<!--</div>-->
                <!--&lt;!&ndash; FOOTER BOX - END &ndash;&gt;-->
                <!-- -->
                <!--&lt;!&ndash; FOOTER BOX - START &ndash;&gt;-->
                <!--<div class="col-sm-6 col-md-4">-->
                	<!--<div class="box footer-tags">-->
						<!--<h4>Tags</h4>-->
                        <!--<a href=""><span class="text-10">Clean</span></a>-->
                        <!--<a href=""><span class="text-20">CV</span></a>-->
                        <!--<a href=""><span class="text-20">Flat</span></a>-->
                        <!--<a href=""><span class="text-14">Freelance</span></a>-->
                        <!--<a href=""><span class="text-20">Modern</span></a>-->
                        <!--<a href=""><span class="text-12">One Page</span></a>-->
                        <!--<a href=""><span class="text-14">Professional</span></a>-->
                        <!--<a href=""><span class="text-14">Responsive</span></a>-->
                        <!--<a href=""><span class="text-16">Resume</span></a>-->
                        <!--<a href=""><span class="text-20">Business</span></a>-->
                        <!--<a href=""><span class="text-16">Corporate</span></a>-->
                        <!--<a href=""><span class="text-18">CSS3</span></a>-->
                        <!--<a href=""><span class="text-12">HTML5</span></a>-->
                        <!--<a href=""><span class="text-16">Mobile First</span></a>-->
                        <!--<a href=""><span class="text-20">Multipurpose</span></a>-->
                        <!--<a href=""><span class="text-14">Portfolio</span></a>                   -->
					<!--</div>-->
            	<!--</div>-->
                <!--&lt;!&ndash; FOOTER BOX - END &ndash;&gt;-->
                <!-- -->
                <!--&lt;!&ndash; FOOTER BOX - START &ndash;&gt;-->
                <!--<div class="col-sm-6 col-md-4 hidden-xs">-->
                	<!--<div class="box footer-posts">-->
                        <!--<h4>Recent Posts</h4>	-->
                        <!--<ul class="list-unstyled">-->
                            <!--<li><a href="#">Pellentesque habitant morbi</a> <span class="post-date">6.2.2015</span></li>-->
                            <!--<li><a href="#">Tristique senectus et netus</a> <span class="post-date">31.1.2015</span></li>-->
                            <!--<li><a href="#">Et malesuada fames ac</a> <span class="post-date">9.12.2014</span></li>-->
                            <!--<li><a href="#">Turpis egestas nullam</a> <span class="post-date">1.12.2014</span></li>-->
                            <!--<li><a href="#">Posuere magna a dapibus luctus</a> <span class="post-date">25.11.2014</span></li>-->
                        <!--</ul>-->
                    <!--</div>-->
            	<!--</div>-->
                <!-- FOOTER BOX - END -->
                
            </div>
        </div>
    	<footer class="navbar navbar-default">
        	<div class="row">
            	<div class="col-md-6 ">
                    <% if user_signed_in? %>
                	<ul class="nav navbar-nav">
                        <li><%= link_to "Home", root_path, method: :get %></li>
                        <li><%= link_to "Profile", profile_user_details_path(:id =>current_user.id), method: :get %></li>
                        <li><%= link_to "Message", messages_path, method: :get %></li>
                        <li><%= link_to "Gallery", gallery_user_details_path(:id =>current_user.id), method: :get %></li>
                        <li><%= link_to "eLEGEND - Terms of Service", terms_of_service_path, method: :get %></li>
                    </ul>
                    <% else %>                   
                    <ul class="nav navbar-nav">
                        <li><%= link_to "eLEGEND - Terms of Service", terms_of_service_path, method: :get %></li>
                        <li><%= link_to "Privacy Policy", terms_of_service_path, method: :get %></li>
                    </ul>
                    <% end %>

                </div>
                <div class="col-md-6">
                    <p class="copyright">© eLegend 2015 All right reserved. Designed by <a href="http://www.thethinktech.com" target="_blank">ThinkTech Software Inc.</a></p>
                </div>
            </div>
        </footer>
    </div>
    <!-- ==========================
    	FOOTER - END 
    =========================== -->


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :index_js %>
<%= yield :signin_js %>
<%= yield :general_js %>
</body>
</html>

app/views/layouts/demo.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <%= favicon_link_tag 'favicon.png' %>
<title>eLegend</title>
<link rel="shortcut icon" href="/assets/icons/favicon.ico">
<link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-touch-icon-114x114.png">

<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<%= yield :index_css %>

<%= csrf_meta_tags %>

</head>
<body>
	
    <!-- ==========================
    	HEADER - START 
    =========================== -->
	<header class="navbar navbar-default navbar-fixed-top">
    	<div class="container">
            <div class="navbar-header">
            	<a href="index.html" class="navbar-brand visible-xs">eLeagend</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="navbar-collapse collapse">
            	<!-- <ul class="nav navbar-nav">
                	<li><a href="/">Home</a></li>
                    <li><a href="team.html">Admin team</a></li>
                    
                    <li><a href="gallery.html">Gallery</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gaming</a>
                        <ul class="dropdown-menu">
                        	<li><a href="gaming-team.html"><i class="fa fa-plus"></i>Gaming team</a></li>
                            <li><a href="matches-list.html"><i class="fa fa-plus"></i>List of matches</a></li>
                            <li><a href="match-single.html"><i class="fa fa-plus"></i>Single match</a></li>
                            <li><a href="tournament.html"><i class="fa fa-plus"></i>Tournament</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Forum</a>
                        <ul class="dropdown-menu">
                        	<li><a href="forum.html"><i class="fa fa-plus"></i>Forum Page</a></li>
                            <li><a href="forum-list.html"><i class="fa fa-plus"></i>Forum threads</a></li>
                            <li><a href="forum-single.html"><i class="fa fa-plus"></i>Single forum post</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages</a>
                        <ul class="dropdown-menu">
                        	<li><a href="signup.html"><i class="fa fa-plus"></i>Sign up</a></li>
                            <li><a href="signin.html"><i class="fa fa-plus"></i>Sign in</a></li>
                            <li><a href="servers.html"><i class="fa fa-plus"></i>Servers</a></li>
                        	<li><a href="404.html"><i class="fa fa-plus"></i>Error Page</a></li>
                        </ul>
                    </li>
                </ul> --> 
                <div class="pull-right navbar-buttons hidden-xs">                	
                    
                    <% if user_signed_in? %>
                      
                      <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-inverse", :method => :delete %>
                    <% else %>
                    
                      <%= link_to 'Login', new_user_session_path, class: "btn btn-inverse" %>
                    <% end %>
                    
                </div>
            </div>
        </div>
    </header>
    <!-- ==========================
    	HEADER - END 
    =========================== --> 
<% if notice %>
    <div class="container">
        <p class="alert alert-success">
            <%= notice %>
        </p>
    </div>
<% end %>

<%= yield %>

<!-- ==========================
        FOOTER - START 
    =========================== -->
    <div class="container">
        <div class="footer-boxes">
            <div class="row">
                        
                <!-- FOOTER BOX - START -->
                <!--<div class="col-md-4 hidden-xs hidden-sm">-->
                    <!--<div class="box">-->
                        <!--<h4>About Us</h4>-->
                        <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam auctor dictum nibh, ac gravida orci porttitor et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac.</p>-->
                    <!--</div>-->
                <!--</div>-->
                <!--&lt;!&ndash; FOOTER BOX - END &ndash;&gt;-->
                <!-- -->
                <!--&lt;!&ndash; FOOTER BOX - START &ndash;&gt;-->
                <!--<div class="col-sm-6 col-md-4">-->
                    <!--<div class="box footer-tags">-->
                        <!--<h4>Tags</h4>-->
                        <!--<a href=""><span class="text-10">Clean</span></a>-->
                        <!--<a href=""><span class="text-20">CV</span></a>-->
                        <!--<a href=""><span class="text-20">Flat</span></a>-->
                        <!--<a href=""><span class="text-14">Freelance</span></a>-->
                        <!--<a href=""><span class="text-20">Modern</span></a>-->
                        <!--<a href=""><span class="text-12">One Page</span></a>-->
                        <!--<a href=""><span class="text-14">Professional</span></a>-->
                        <!--<a href=""><span class="text-14">Responsive</span></a>-->
                        <!--<a href=""><span class="text-16">Resume</span></a>-->
                        <!--<a href=""><span class="text-20">Business</span></a>-->
                        <!--<a href=""><span class="text-16">Corporate</span></a>-->
                        <!--<a href=""><span class="text-18">CSS3</span></a>-->
                        <!--<a href=""><span class="text-12">HTML5</span></a>-->
                        <!--<a href=""><span class="text-16">Mobile First</span></a>-->
                        <!--<a href=""><span class="text-20">Multipurpose</span></a>-->
                        <!--<a href=""><span class="text-14">Portfolio</span></a>                   -->
                    <!--</div>-->
                <!--</div>-->
                <!--&lt;!&ndash; FOOTER BOX - END &ndash;&gt;-->
                <!-- -->
                <!--&lt;!&ndash; FOOTER BOX - START &ndash;&gt;-->
                <!--<div class="col-sm-6 col-md-4 hidden-xs">-->
                    <!--<div class="box footer-posts">-->
                        <!--<h4>Recent Posts</h4>   -->
                        <!--<ul class="list-unstyled">-->
                            <!--<li><a href="#">Pellentesque habitant morbi</a> <span class="post-date">6.2.2015</span></li>-->
                            <!--<li><a href="#">Tristique senectus et netus</a> <span class="post-date">31.1.2015</span></li>-->
                            <!--<li><a href="#">Et malesuada fames ac</a> <span class="post-date">9.12.2014</span></li>-->
                            <!--<li><a href="#">Turpis egestas nullam</a> <span class="post-date">1.12.2014</span></li>-->
                            <!--<li><a href="#">Posuere magna a dapibus luctus</a> <span class="post-date">25.11.2014</span></li>-->
                        <!--</ul>-->
                    <!--</div>-->
                <!--</div>-->
                <!-- FOOTER BOX - END -->
                
            </div>
        </div>
        <footer class="navbar navbar-default">
            <div class="row">
                <div class="col-md-6 hidden-xs hidden-sm">
                    <!-- <ul class="nav navbar-nav">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="team.html">Admin team</a></li>
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="tournament.html">Tournament</a></li>
                        <li><a href="gallery.html">Gallery</a></li>
                        <li><a href="forum.html">Forum</a></li>
                    </ul> -->
                </div>
                <div class="col-md-6">
                    <p class="copyright">© eLegend 2015 All right reserved. Designed by <a href="http://www.thethinktech.com" target="_blank">ThinkTech Software Inc.</a></p>
                </div>
            </div>
        </footer>
    </div>
    <!-- ==========================
        FOOTER - END 
    =========================== -->


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :index_js %>
</body>
</html>